# Generated by Django 5.2.8 on 2025-11-13 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('blocked', 'Заблокирована'), ('pending', 'Приостановлена'), ('testing', 'Тестирование'), ('inreview', 'На проверке'), ('done', 'Завершена')], default='new', max_length=15)),
                ('priority', models.CharField(choices=[('5', 'Немедленный'), ('4', 'Главный'), ('3', 'Высокий'), ('2', 'Средний'), ('1', 'Низкий')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.project')),
            ],
        ),
    ]
